server:
  port: 0

spring:
  application:
    name: chatgpt-service
  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: "*"

#chatgpt:
#  api-key: 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
