server:
  port: 9001

spring:
  application:
    name: gateway
  profiles:
    active: prod
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/login/oauth2/**, /oauth2/**, /api/auth/**

        - id: service-discovery
          uri: lb://SERVICE-DISCOVERY
          predicates:
            - Path=/api/client/**

        - id: song-service
          uri: lb://SONG-SERVICE
          predicates:
            - Path=/api/song/**
#          filters:
#            - AuthorizationHeaderFilter
        - id: show-service
          uri: lb://SHOW-SERVICE
          predicates:
            - Path=/api/show/**

        - id: drama-service
          uri: lb://drama-SERVICE
          predicates:
            - Path=/api/drama/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

management:
  endpoints:
    web:
      exposure:
        include: "*"